name: Pre-Deploy Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-deploy-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_URL: https://example.com
          SENTRY_ORG: devpowerbg-ltd
          SENTRY_PROJECT: toki

      - name: Security audit
        run: pnpm audit --audit-level=high
        continue-on-error: true

      - name: Pre-deploy summary
        run: |
          echo "✅ All pre-deploy checks passed!"
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "🔍 This is a PR - no deployment will occur"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "🚀 This is main branch - ready for deployment"
          else
            echo "📝 This is a feature branch - no deployment will occur"
          fi
